# Generated by Django 5.0.14 on 2026-10-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('solve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/explanations/')),
                ('text_content', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_explanations', to='solve.userattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_explanations', to='questions.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
