# Generated by Django 5.0.14 on 2026-10-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('solve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempt',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='questions.question'),
        ),
    ]
