# Generated by Django 5.0.14 on 2026-10-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedquestion',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedquestion',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedquestion',
            name='ocr_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedquestion',
            name='question_candidates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='uploadedquestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ocr_completed', 'OCR Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
